const KEY="accounting-project-transactions-v3";
const OLD="accounting-project-transactions-v2";
const categories={income:["Xizmat","Savdo","Avans","Boshqa daromad"],expense:["Ijara","Ish haqi","Soliq","Reklama","Transport","Ofis","Boshqa xarajat"]};
let editingId=null;
let transactions=load();let customers=JSON.parse(localStorage.getItem("accounting-customers")||"[]");let debts=JSON.parse(localStorage.getItem("accounting-debts")||"[]");let invoices=JSON.parse(localStorage.getItem("accounting-invoices")||"[]");let services=JSON.parse(localStorage.getItem("accounting-services")||"[]");let products=JSON.parse(localStorage.getItem("accounting-products")||"[]");let productTab="sale";

function load(){try{let raw=localStorage.getItem(KEY);if(!raw){raw=localStorage.getItem(OLD);if(raw)localStorage.setItem(KEY,raw)}const a=JSON.parse(raw||"[]");return Array.isArray(a)?a.map((x,i)=>({...x,id:x.id||String(Date.now()+i),category:x.category||(x.type==="income"?"Boshqa daromad":"Boshqa xarajat"),date:x.date||(x.createdAt||new Date().toISOString()).slice(0,10),note:x.note||""})):[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(transactions))}
function money(v){return new Intl.NumberFormat("uz-UZ",{maximumFractionDigits:2}).format(v)+" so‘m"}
function esc(v){const e=document.createElement("span");e.textContent=v||"";return e.innerHTML}
function dateFmt(v){const d=new Date(v+"T00:00:00");return new Intl.DateTimeFormat("uz-UZ",{year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function filtered(){const q=document.getElementById("search").value.trim().toLowerCase(),t=document.getElementById("filterType").value,c=document.getElementById("filterCategory").value,m=document.getElementById("filterMonth").value;return transactions.filter(x=>(!q||(x.description+" "+x.category+" "+x.note).toLowerCase().includes(q))&&(t==="all"||x.type===t)&&(c==="all"||x.category===c)&&(!m||x.date.startsWith(m)))}
function totals(items){return items.reduce((a,x)=>{a[x.type]+=Number(x.amount)||0;return a},{income:0,expense:0})}
function populateCategory(type,selected){const el=document.getElementById("category");el.innerHTML=categories[type].map(c=>'<option '+(c===selected?"selected":"")+'>'+c+'</option>').join("")}
function refreshFilterCategories(){const el=document.getElementById("filterCategory"),val=el.value;const all=[...new Set([...categories.income,...categories.expense,...transactions.map(x=>x.category)])];el.innerHTML='<option value="all">Barcha kategoriyalar</option>'+all.map(c=>'<option>'+esc(c)+'</option>').join("");if([...el.options].some(o=>o.value===val))el.value=val}
function render(){
 const list=filtered(),all=totals(transactions),report=totals(list);
 document.getElementById("income").textContent=money(all.income);document.getElementById("expense").textContent=money(all.expense);document.getElementById("balance").textContent=money(all.income-all.expense);document.getElementById("opCount").textContent=transactions.length;
 document.getElementById("reportIncome").textContent=money(report.income);document.getElementById("reportExpense").textContent=money(report.expense);document.getElementById("reportBalance").textContent=money(report.income-report.expense);
 const tbody=document.getElementById("transactions");tbody.innerHTML=list.map(x=>'<tr><td>'+dateFmt(x.date)+'</td><td><b>'+esc(x.description)+'</b>'+(x.note?'<br><small>'+esc(x.note)+'</small>':'')+'</td><td>'+esc(x.category)+'</td><td><span class="badge">'+(x.type==="income"?"Daromad":"Xarajat")+'</span></td><td class="amount">'+money(x.amount)+'</td><td class="actions"><button class="edit" data-edit="'+x.id+'">Tahrirlash</button><button class="delete" data-del="'+x.id+'">O‘chirish</button></td></tr>').join("");
 document.getElementById("empty").classList.toggle("hidden",list.length>0);
 document.getElementById("recent").innerHTML=transactions.slice(0,5).map(x=>'<div class="recent-row"><div><b>'+esc(x.description)+'</b><br><small>'+dateFmt(x.date)+' · '+esc(x.category)+'</small></div><strong>'+money(x.amount)+'</strong></div>').join("")||'<p class="muted">Hozircha ma’lumot yo‘q.</p>';
 const map={};transactions.filter(x=>x.type==="expense").forEach(x=>map[x.category]=(map[x.category]||0)+x.amount);document.getElementById("categorySummary").innerHTML=Object.entries(map).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,6).map(([k,v])=>'<div class="category-row"><span>'+esc(k)+'</span><b>'+money(v)+'</b></div>').join("")||'<p class="muted">Hozircha ma’lumot yo‘q.</p>';
 document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openModal(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>remove(b.dataset.del));
}
function openModal(id=null){editingId=id;const x=id?transactions.find(t=>t.id===id):null;document.getElementById("modalTitle").textContent=x?"Operatsiyani tahrirlash":"Yangi operatsiya";document.getElementById("description").value=x?.description||"";document.getElementById("amount").value=x?.amount||"";document.getElementById("type").value=x?.type||"income";document.getElementById("chooseIncome").classList.toggle("active",(x?.type||"income")==="income");document.getElementById("chooseExpense").classList.toggle("active",(x?.type||"income")==="expense");populateCategory(x?.type||"income",x?.category);document.getElementById("date").value=x?.date||new Date().toISOString().slice(0,10);document.getElementById("note").value=x?.note||"";document.getElementById("message").textContent="";document.getElementById("modal").classList.remove("hidden");document.getElementById("description").focus()}
function closeModal(){document.getElementById("modal").classList.add("hidden");editingId=null}
function submit(){const d=document.getElementById("description").value.trim(),a=Number(document.getElementById("amount").value),type=document.getElementById("type").value,category=document.getElementById("category").value,date=document.getElementById("date").value,note=document.getElementById("note").value.trim();if(!d||!Number.isFinite(a)||a<=0||!date){document.getElementById("message").textContent="Nomi, sana va 0 dan katta summa kiritilishi shart.";return}const item={id:editingId||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now())),description:d,amount:a,type,category,date,note,createdAt:new Date().toISOString()};if(editingId){transactions=transactions.map(x=>x.id===editingId?item:x)}else transactions.unshift(item);save();refreshFilterCategories();render();closeModal()}
function remove(id){if(confirm("Ushbu operatsiyani o‘chirasizmi?")){transactions=transactions.filter(x=>x.id!==id);save();refreshFilterCategories();render()}}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===id));document.getElementById("pageTitle").textContent={dashboard:"Bosh sahifa",operations:"Kirim-chiqim",customers:"Mijozlar",debts:"Qarzdorlik",services:"Xizmatlar",products:"Tovarlar",invoices:"Hisob-fakturalar",reports:"Hisobot"}[id];document.getElementById("pageHelp").textContent={dashboard:"Pul qayerdan keldi va qayerga ketdi — shu yerda ko‘rasiz.",operations:"Barcha pul harakatlari bitta joyda.",customers:"Mijozlaringizni eslab qolish oson.",debts:"Kim kimga qancha qarz — aniq ko‘rinadi.",services:"Sotadigan xizmatlaringiz va narxlari.",products:"Tovar va ishlab chiqarish mahsulotlari.",invoices:"Mijozga yozilgan hisob va uning to‘lov holati.",reports:"Hisobingizning sodda xulosasi."}[id]}
function exportCsv(){const rows=[["Sana","Nomi","Kategoriya","Turi","Summa","Izoh"],...filtered().map(x=>[x.date,x.description,x.category,x.type==="income"?"Daromad":"Xarajat",x.amount,x.note])];const csv="\uFEFF"+rows.map(r=>r.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(";")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="accounting-report.csv";a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>showView(n.dataset.view));document.querySelectorAll("[data-go]").forEach(n=>n.onclick=()=>showView(n.dataset.go));document.getElementById("newBtn").onclick=()=>openModal();document.getElementById("closeModal").onclick=closeModal;document.getElementById("cancel").onclick=closeModal;document.getElementById("saveTransaction").onclick=submit;function chooseType(type){document.getElementById("type").value=type;document.getElementById("chooseIncome").classList.toggle("active",type==="income");document.getElementById("chooseExpense").classList.toggle("active",type==="expense");populateCategory(type)}document.getElementById("chooseIncome").onclick=()=>chooseType("income");document.getElementById("chooseExpense").onclick=()=>chooseType("expense");document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>{openModal();chooseType(b.dataset.quick)});["search","filterType","filterCategory","filterMonth"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",render));document.getElementById("resetFilters").onclick=()=>{document.getElementById("search").value="";document.getElementById("filterType").value="all";document.getElementById("filterCategory").value="all";document.getElementById("filterMonth").value="";render()};document.getElementById("exportCsv").onclick=exportCsv;document.getElementById("clearAll").onclick=()=>{if(transactions.length&&confirm("BARCHA ma’lumotlar o‘chiriladi. Davom etasizmi?")){transactions=[];save();refreshFilterCategories();render()}};document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});refreshFilterCategories();populateCategory("income");render();
function id(){return (crypto.randomUUID&&crypto.randomUUID())||String(Date.now()+Math.random())}
function renderCustomers(){const q=document.getElementById("customerSearch").value.toLowerCase();const list=customers.filter(x=>(x.name+" "+x.phone+" "+x.tin).toLowerCase().includes(q));document.getElementById("customerList").innerHTML=list.map(x=>'<div class="person-row"><div class="avatar">'+esc(x.name.slice(0,1).toUpperCase())+'</div><div class="person-main"><b>'+esc(x.name)+'</b><small>'+esc([x.phone,x.tin&&"STIR: "+x.tin].filter(Boolean).join(" · ")||"Qo‘shimcha ma’lumot yo‘q")+'</small></div><button class="delete" data-cdel="'+x.id+'">O‘chirish</button></div>').join("");document.getElementById("customerEmpty").classList.toggle("hidden",list.length>0);document.querySelectorAll("[data-cdel]").forEach(b=>b.onclick=()=>{if(confirm("Mijozni o‘chirasizmi?")){customers=customers.filter(x=>x.id!==b.dataset.cdel);localStorage.setItem("accounting-customers",JSON.stringify(customers));renderCustomers()}})}
function renderDebts(){const t=debts.reduce((a,x)=>{a[x.type]+=Number(x.amount);return a},{receivable:0,payable:0});document.getElementById("receivable").textContent=money(t.receivable);document.getElementById("payable").textContent=money(t.payable);document.getElementById("debtNet").textContent=money(t.receivable-t.payable);document.getElementById("debtList").innerHTML=debts.map(x=>'<div class="person-row"><div class="debt-dot '+x.type+'"></div><div class="person-main"><b>'+esc(x.person)+'</b><small>'+(x.type==="receivable"?"Sizga beradi":"Siz berasiz")+(x.due?" · Muddat: "+dateFmt(x.due):"")+(x.note?" · "+esc(x.note):"")+'</small></div><strong>'+money(x.amount)+'</strong><button class="delete" data-ddel="'+x.id+'">O‘chirish</button></div>').join("");document.getElementById("debtEmpty").classList.toggle("hidden",debts.length>0);document.querySelectorAll("[data-ddel]").forEach(b=>b.onclick=()=>{if(confirm("Qarzdorlikni o‘chirasizmi?")){debts=debts.filter(x=>x.id!==b.dataset.ddel);localStorage.setItem("accounting-debts",JSON.stringify(debts));renderDebts()}})}
document.getElementById("addCustomer").onclick=()=>document.getElementById("customerModal").classList.remove("hidden");document.getElementById("saveCustomer").onclick=()=>{const name=document.getElementById("customerName").value.trim();if(!name){document.getElementById("customerMessage").textContent="Mijoz nomini yozing.";return}customers.unshift({id:id(),name,phone:document.getElementById("customerPhone").value.trim(),tin:document.getElementById("customerTin").value.trim()});localStorage.setItem("accounting-customers",JSON.stringify(customers));["customerName","customerPhone","customerTin"].forEach(x=>document.getElementById(x).value="");document.getElementById("customerMessage").textContent="";document.getElementById("customerModal").classList.add("hidden");renderCustomers()};
document.getElementById("customerSearch").oninput=renderCustomers;document.getElementById("addDebt").onclick=()=>document.getElementById("debtModal").classList.remove("hidden");function debtChoice(t){document.getElementById("debtType").value=t;document.getElementById("chooseReceivable").classList.toggle("active",t==="receivable");document.getElementById("choosePayable").classList.toggle("active",t==="payable")}document.getElementById("chooseReceivable").onclick=()=>debtChoice("receivable");document.getElementById("choosePayable").onclick=()=>debtChoice("payable");document.getElementById("saveDebt").onclick=()=>{const person=document.getElementById("debtPerson").value.trim(),amount=Number(document.getElementById("debtAmount").value);if(!person||!amount||amount<=0){document.getElementById("debtMessage").textContent="Kimligini va summani yozing.";return}debts.unshift({id:id(),person,amount,type:document.getElementById("debtType").value,due:document.getElementById("debtDue").value,note:document.getElementById("debtNote").value.trim()});localStorage.setItem("accounting-debts",JSON.stringify(debts));["debtPerson","debtAmount","debtDue","debtNote"].forEach(x=>document.getElementById(x).value="");document.getElementById("debtMessage").textContent="";document.getElementById("debtModal").classList.add("hidden");renderDebts()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add("hidden"));renderCustomers();renderDebts();
function invoiceCustomers(){const s=document.getElementById("invoiceCustomer");s.innerHTML=customers.length?customers.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join(""):'<option value="">Avval mijoz qo‘shing</option>'}
function renderInvoices(){const total=invoices.reduce((a,x)=>a+Number(x.amount),0),paid=invoices.filter(x=>x.paid).reduce((a,x)=>a+Number(x.amount),0);document.getElementById("invoiceTotal").textContent=money(total);document.getElementById("invoicePaid").textContent=money(paid);document.getElementById("invoiceUnpaid").textContent=money(total-paid);document.getElementById("invoiceList").innerHTML=invoices.map(x=>'<div class="invoice-row"><div class="person-main"><b>'+esc(x.description)+'</b><small>'+esc(x.customerName)+' · Muddat: '+dateFmt(x.due)+'</small></div><strong>'+money(x.amount)+'</strong><span class="status '+(x.paid?"paid":"waiting")+'">'+(x.paid?"To‘langan":"Kutilmoqda")+'</span>'+(x.paid?'':'<button class="edit" data-pay="'+x.id+'">✓ To‘landi</button>')+'<button class="delete" data-idel="'+x.id+'">O‘chirish</button></div>').join("");document.getElementById("invoiceEmpty").classList.toggle("hidden",invoices.length>0);document.querySelectorAll("[data-pay]").forEach(b=>b.onclick=()=>{const x=invoices.find(i=>i.id===b.dataset.pay);if(x){x.paid=true;x.paidAt=new Date().toISOString();transactions.unshift({id:id(),description:"Hisob to‘lovi: "+x.description,amount:Number(x.amount),type:"income",category:"Xizmat",date:new Date().toISOString().slice(0,10),note:x.customerName,createdAt:new Date().toISOString()});save();localStorage.setItem("accounting-invoices",JSON.stringify(invoices));render();renderInvoices()}});document.querySelectorAll("[data-idel]").forEach(b=>b.onclick=()=>{if(confirm("Hisob-fakturani o‘chirasizmi?")){invoices=invoices.filter(x=>x.id!==b.dataset.idel);localStorage.setItem("accounting-invoices",JSON.stringify(invoices));renderInvoices()}})}
document.getElementById("addInvoice").onclick=()=>{invoiceCustomers();document.getElementById("invoiceDue").value=new Date().toISOString().slice(0,10);document.getElementById("invoiceModal").classList.remove("hidden")};document.getElementById("saveInvoice").onclick=()=>{const cid=document.getElementById("invoiceCustomer").value,cust=customers.find(x=>x.id===cid),description=document.getElementById("invoiceDescription").value.trim(),amount=Number(document.getElementById("invoiceAmount").value),due=document.getElementById("invoiceDue").value;if(!cust||!description||!amount||amount<=0||!due){document.getElementById("invoiceMessage").textContent=cust?"Barcha asosiy joylarni to‘ldiring.":"Avval Mijozlar bo‘limida mijoz qo‘shing.";return}invoices.unshift({id:id(),customerId:cid,customerName:cust.name,description,amount,due,paid:false,createdAt:new Date().toISOString()});localStorage.setItem("accounting-invoices",JSON.stringify(invoices));document.getElementById("invoiceDescription").value="";document.getElementById("invoiceAmount").value="";document.getElementById("invoiceMessage").textContent="";document.getElementById("invoiceModal").classList.add("hidden");renderInvoices()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add("hidden"));renderInvoices();
function renderServices(){document.getElementById("serviceList").innerHTML=services.map(x=>'<div class="person-row"><div class="avatar">🛠</div><div class="person-main"><b>'+esc(x.name)+'</b><small>'+esc(x.note||"Xizmat")+'</small></div><strong>'+money(x.price)+'</strong><button class="delete" data-sdel="'+x.id+'">O‘chirish</button></div>').join("");document.getElementById("serviceEmpty").classList.toggle("hidden",services.length>0);document.querySelectorAll("[data-sdel]").forEach(b=>b.onclick=()=>{if(confirm("Xizmatni o‘chirasizmi?")){services=services.filter(x=>x.id!==b.dataset.sdel);localStorage.setItem("accounting-services",JSON.stringify(services));renderServices()}})}
document.getElementById("addService").onclick=()=>document.getElementById("serviceModal").classList.remove("hidden");document.getElementById("saveService").onclick=()=>{const name=document.getElementById("serviceName").value.trim(),price=Number(document.getElementById("servicePrice").value);if(!name||price<0||!Number.isFinite(price)){document.getElementById("serviceMessage").textContent="Xizmat nomi va narxini kiriting.";return}services.unshift({id:id(),name,price,note:document.getElementById("serviceNote").value.trim()});localStorage.setItem("accounting-services",JSON.stringify(services));["serviceName","servicePrice","serviceNote"].forEach(x=>document.getElementById(x).value="");document.getElementById("serviceMessage").textContent="";document.getElementById("serviceModal").classList.add("hidden");renderServices()};
const productNames={sale:"Sotiladigan tovarlar",finished:"Ishlab chiqarilgan mahsulotlar",semi:"Yarim tayyor mahsulotlar"};function renderProducts(){const list=products.filter(x=>x.kind===productTab);document.getElementById("productHeading").textContent=productNames[productTab];document.getElementById("productList").innerHTML=list.map(x=>'<div class="product-row"><div class="avatar">'+(x.kind==="sale"?"🛒":x.kind==="finished"?"🏭":"⚙️")+'</div><div class="person-main"><b>'+esc(x.name)+'</b><small>Omborda: '+x.qty+" "+esc(x.unit)+' · Tannarx: '+money(x.cost)+'</small></div><div class="price-box"><small>Sotuv narxi</small><strong>'+money(x.price)+'</strong></div><button class="delete" data-pdel="'+x.id+'">O‘chirish</button></div>').join("");document.getElementById("productEmpty").classList.toggle("hidden",list.length>0);document.querySelectorAll("[data-pdel]").forEach(b=>b.onclick=()=>{if(confirm("Mahsulotni o‘chirasizmi?")){products=products.filter(x=>x.id!==b.dataset.pdel);localStorage.setItem("accounting-products",JSON.stringify(products));renderProducts()}})}
document.querySelectorAll("[data-product-tab]").forEach(b=>b.onclick=()=>{productTab=b.dataset.productTab;document.querySelectorAll("[data-product-tab]").forEach(x=>x.classList.toggle("active",x===b));renderProducts()});document.getElementById("addProduct").onclick=()=>{document.getElementById("productModalTitle").textContent="Yangi: "+productNames[productTab].replace(/lar$/,"");document.getElementById("productModal").classList.remove("hidden")};document.getElementById("saveProduct").onclick=()=>{const name=document.getElementById("productName").value.trim(),qty=Number(document.getElementById("productQty").value),cost=Number(document.getElementById("productCost").value),price=Number(document.getElementById("productPrice").value);if(!name||[qty,cost,price].some(x=>!Number.isFinite(x)||x<0)){document.getElementById("productMessage").textContent="Nomi, miqdori va narxlarni to‘g‘ri kiriting.";return}products.unshift({id:id(),kind:productTab,name,qty,unit:document.getElementById("productUnit").value,cost,price});localStorage.setItem("accounting-products",JSON.stringify(products));["productName","productQty","productCost","productPrice"].forEach(x=>document.getElementById(x).value="");document.getElementById("productMessage").textContent="";document.getElementById("productModal").classList.add("hidden");renderProducts()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add("hidden"));renderServices();renderProducts();