const KEY="accounting-project-transactions-v3";
const OLD="accounting-project-transactions-v2";
const categories={income:["Xizmat","Savdo","Avans","Boshqa daromad"],expense:["Ijara","Ish haqi","Soliq","Reklama","Transport","Ofis","Boshqa xarajat"]};
let editingId=null;
let transactions=load();

function load(){try{let raw=localStorage.getItem(KEY);if(!raw){raw=localStorage.getItem(OLD);if(raw)localStorage.setItem(KEY,raw)}const a=JSON.parse(raw||"[]");return Array.isArray(a)?a.map((x,i)=>({...x,id:x.id||String(Date.now()+i),category:x.category||(x.type==="income"?"Boshqa daromad":"Boshqa xarajat"),date:x.date||(x.createdAt||new Date().toISOString()).slice(0,10),note:x.note||""})):[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(transactions))}
function money(v){return new Intl.NumberFormat("uz-UZ",{maximumFractionDigits:2}).format(v)+" so‘m"}
function esc(v){const e=document.createElement("span");e.textContent=v||"";return e.innerHTML}
function dateFmt(v){const d=new Date(v+"T00:00:00");return new Intl.DateTimeFormat("uz-UZ",{year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function filtered(){const q=document.getElementById("search").value.trim().toLowerCase(),t=document.getElementById("filterType").value,c=document.getElementById("filterCategory").value,m=document.getElementById("filterMonth").value;return transactions.filter(x=>(!q||(x.description+" "+x.category+" "+x.note).toLowerCase().includes(q))&&(t==="all"||x.type===t)&&(c==="all"||x.category===c)&&(!m||x.date.startsWith(m)))}
function totals(items){return items.reduce((a,x)=>{a[x.type]+=Number(x.amount)||0;return a},{income:0,expense:0})}
function populateCategory(type,selected){const el=document.getElementById("category");el.innerHTML=categories[type].map(c=>'<option '+(c===selected?"selected":"")+'>'+c+'</option>').join("")}
function refreshFilterCategories(){const el=document.getElementById("filterCategory"),val=el.value;const all=[...new Set([...categories.income,...categories.expense,...transactions.map(x=>x.category)])];el.innerHTML='<option value="all">Barcha kategoriyalar</option>'+all.map(c=>'<option>'+esc(c)+'</option>').join("");if([...el.options].some(o=>o.value===val))el.value=val}
function render(){
 const list=filtered(),all=totals(transactions),report=totals(list);
 document.getElementById("income").textContent=money(all.income);document.getElementById("expense").textContent=money(all.expense);document.getElementById("balance").textContent=money(all.income-all.expense);document.getElementById("opCount").textContent=transactions.length;
 document.getElementById("reportIncome").textContent=money(report.income);document.getElementById("reportExpense").textContent=money(report.expense);document.getElementById("reportBalance").textContent=money(report.income-report.expense);
 const tbody=document.getElementById("transactions");tbody.innerHTML=list.map(x=>'<tr><td>'+dateFmt(x.date)+'</td><td><b>'+esc(x.description)+'</b>'+(x.note?'<br><small>'+esc(x.note)+'</small>':'')+'</td><td>'+esc(x.category)+'</td><td><span class="badge">'+(x.type==="income"?"Daromad":"Xarajat")+'</span></td><td class="amount">'+money(x.amount)+'</td><td class="actions"><button class="edit" data-edit="'+x.id+'">Tahrirlash</button><button class="delete" data-del="'+x.id+'">O‘chirish</button></td></tr>').join("");
 document.getElementById("empty").classList.toggle("hidden",list.length>0);
 document.getElementById("recent").innerHTML=transactions.slice(0,5).map(x=>'<div class="recent-row"><div><b>'+esc(x.description)+'</b><br><small>'+dateFmt(x.date)+' · '+esc(x.category)+'</small></div><strong>'+money(x.amount)+'</strong></div>').join("")||'<p class="muted">Hozircha ma’lumot yo‘q.</p>';
 const map={};transactions.filter(x=>x.type==="expense").forEach(x=>map[x.category]=(map[x.category]||0)+x.amount);document.getElementById("categorySummary").innerHTML=Object.entries(map).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,6).map(([k,v])=>'<div class="category-row"><span>'+esc(k)+'</span><b>'+money(v)+'</b></div>').join("")||'<p class="muted">Hozircha ma’lumot yo‘q.</p>';
 document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openModal(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>remove(b.dataset.del));
}
function openModal(id=null){editingId=id;const x=id?transactions.find(t=>t.id===id):null;document.getElementById("modalTitle").textContent=x?"Operatsiyani tahrirlash":"Yangi operatsiya";document.getElementById("description").value=x?.description||"";document.getElementById("amount").value=x?.amount||"";document.getElementById("type").value=x?.type||"income";document.getElementById("chooseIncome").classList.toggle("active",(x?.type||"income")==="income");document.getElementById("chooseExpense").classList.toggle("active",(x?.type||"income")==="expense");populateCategory(x?.type||"income",x?.category);document.getElementById("date").value=x?.date||new Date().toISOString().slice(0,10);document.getElementById("note").value=x?.note||"";document.getElementById("message").textContent="";document.getElementById("modal").classList.remove("hidden");document.getElementById("description").focus()}
function closeModal(){document.getElementById("modal").classList.add("hidden");editingId=null}
function submit(){const d=document.getElementById("description").value.trim(),a=Number(document.getElementById("amount").value),type=document.getElementById("type").value,category=document.getElementById("category").value,date=document.getElementById("date").value,note=document.getElementById("note").value.trim();if(!d||!Number.isFinite(a)||a<=0||!date){document.getElementById("message").textContent="Nomi, sana va 0 dan katta summa kiritilishi shart.";return}const item={id:editingId||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now())),description:d,amount:a,type,category,date,note,createdAt:new Date().toISOString()};if(editingId){transactions=transactions.map(x=>x.id===editingId?item:x)}else transactions.unshift(item);save();refreshFilterCategories();render();closeModal()}
function remove(id){if(confirm("Ushbu operatsiyani o‘chirasizmi?")){transactions=transactions.filter(x=>x.id!==id);save();refreshFilterCategories();render()}}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===id));document.getElementById("pageTitle").textContent={dashboard:"Dashboard",operations:"Operatsiyalar",reports:"Hisobotlar"}[id]}
function exportCsv(){const rows=[["Sana","Nomi","Kategoriya","Turi","Summa","Izoh"],...filtered().map(x=>[x.date,x.description,x.category,x.type==="income"?"Daromad":"Xarajat",x.amount,x.note])];const csv="\uFEFF"+rows.map(r=>r.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(";")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="accounting-report.csv";a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>showView(n.dataset.view));document.querySelectorAll("[data-go]").forEach(n=>n.onclick=()=>showView(n.dataset.go));document.getElementById("newBtn").onclick=()=>openModal();document.getElementById("closeModal").onclick=closeModal;document.getElementById("cancel").onclick=closeModal;document.getElementById("saveTransaction").onclick=submit;function chooseType(type){document.getElementById("type").value=type;document.getElementById("chooseIncome").classList.toggle("active",type==="income");document.getElementById("chooseExpense").classList.toggle("active",type==="expense");populateCategory(type)}document.getElementById("chooseIncome").onclick=()=>chooseType("income");document.getElementById("chooseExpense").onclick=()=>chooseType("expense");document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>{openModal();chooseType(b.dataset.quick)});["search","filterType","filterCategory","filterMonth"].forEach(id=>document.getElementById(id).addEventListener(id==="search"?"input":"change",render));document.getElementById("resetFilters").onclick=()=>{document.getElementById("search").value="";document.getElementById("filterType").value="all";document.getElementById("filterCategory").value="all";document.getElementById("filterMonth").value="";render()};document.getElementById("exportCsv").onclick=exportCsv;document.getElementById("clearAll").onclick=()=>{if(transactions.length&&confirm("BARCHA ma’lumotlar o‘chiriladi. Davom etasizmi?")){transactions=[];save();refreshFilterCategories();render()}};document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});refreshFilterCategories();populateCategory("income");render();